/**
 * TypeScript bindings for Tauri commands
 * This file is auto-generated by tauri-specta during development builds
 * Manual stub provided for standalone TypeScript checking
 */

import { invoke } from "@tauri-apps/api/core";

// Command interface matching Rust backend
export const commands = {
  /**
   * Cancel any ongoing operation
   */
  cancelOperation: async (): Promise<void> => {
    await invoke("cancel_operation");
  },

  /**
   * Cancel ongoing dictation
   */
  cancelDictation: async (): Promise<void> => {
    await invoke("cancel_dictation");
  },
};
